version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo_network
  
  # Node.js API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/todo-app
      - SECRET_TOKEN=${SECRET_TOKEN:-default_secret_token_replace_in_production}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
